services:

  # =========================
  # API Gateway
  # =========================

  api-gateway:
    container_name: api-gateway
    image: ${DOCKERHUB_USERNAME}/api-gateway@${API_GATEWAY_DIGEST}
#    image: ${DOCKERHUB_USERNAME}/api-gateway:${IMAGE_TAG}

    environment:
      SPRING_PROFILES_ACTIVE: prod
      AUTH_SERVICE_URL: http://auth-service:4005

      JAVA_TOOL_OPTIONS: "-javaagent:/otel/opentelemetry-javaagent.jar"

      OTEL_SERVICE_NAME: "api-gateway"
      OTEL_RESOURCE_ATTRIBUTES: "deployment.environment=staging"

      OTEL_TRACES_EXPORTER: "otlp"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://signoz-ingester-1:4317"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"

      OTEL_METRICS_EXPORTER: "none"
      OTEL_LOGS_EXPORTER: "none"
      OTEL_TRACES_SAMPLER: "always_on"

    volumes:
      - /opt/opentelemetry/opentelemetry-javaagent.jar:/otel/opentelemetry-javaagent.jar:ro

    ports:
      - "4004:4004"

    networks:
      - backend-api
      - signoz-network

    depends_on:
      auth-service:
        condition: service_healthy
      patient-service:
        condition: service_healthy
      billing-service:
        condition: service_healthy
      analytics-service:
        condition: service_healthy

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4004/actuator/health"]
      interval: 10s
      timeout: 15s
      retries: 30
      start_period: 180s


  # =========================
  # Patient Service
  # =========================

  patient-service:
    container_name: patient-service
    image: ${DOCKERHUB_USERNAME}/patient-service@${PATIENT_SERVICE_DIGEST}
#    image: ${DOCKERHUB_USERNAME}/patient-service:${IMAGE_TAG}

    environment:
      SPRING_PROFILES_ACTIVE: staging

      SPRING_DATASOURCE_URL: "${PATIENT_SPRING_DATASOURCE_URL}"
      SPRING_DATASOURCE_USERNAME: "${PATIENT_SPRING_DATASOURCE_USERNAME}"
      SPRING_DATASOURCE_PASSWORD: "${PATIENT_SPRING_DATASOURCE_PASSWORD}"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "${PATIENT_SPRING_JPA_HIBERNATE_DDL_AUTO}"
      SPRING_SQL_INIT_MODE: "${PATIENT_SPRING_SQL_INIT_MODE}"

      JWT_SECRET: "${JWT_SECRET}"

      BILLING_SERVICE_ADDRESS: "billing-service"
      BILLING_SERVICE_GRPC_PORT: "9001"

      SPRING_KAFKA_BOOTSTRAP_SERVERS: "${SPRING_KAFKA_BOOTSTRAP_SERVERS}"

      JAVA_TOOL_OPTIONS: "-javaagent:/otel/opentelemetry-javaagent.jar"

      OTEL_SERVICE_NAME: "patient-service"
      OTEL_RESOURCE_ATTRIBUTES: "deployment.environment=staging"

      OTEL_TRACES_EXPORTER: "otlp"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://signoz-ingester-1:4317"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"

      OTEL_METRICS_EXPORTER: "otlp"
      OTEL_LOGS_EXPORTER: "otlp"
      OTEL_TRACES_SAMPLER: "always_on"

    volumes:
      - /opt/opentelemetry/opentelemetry-javaagent.jar:/otel/opentelemetry-javaagent.jar:ro

    extra_hosts:
      - "host.docker.internal:host-gateway"

    networks:
      - backend-api
      - signoz-network

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/actuator/health"]
      interval: 10s
      timeout: 15s
      retries: 30
      start_period: 180s


  # =========================
  # Auth Service
  # =========================

  auth-service:
    container_name: auth-service
#    image: ${DOCKERHUB_USERNAME}/auth-service:${IMAGE_TAG}
    image: ${DOCKERHUB_USERNAME}/auth-service@${AUTH_SERVICE_DIGEST}

    environment:
      SPRING_PROFILES_ACTIVE: staging

      SPRING_DATASOURCE_URL: "${AUTH_SPRING_DATASOURCE_URL}"
      SPRING_DATASOURCE_USERNAME: "${AUTH_SPRING_DATASOURCE_USERNAME}"
      SPRING_DATASOURCE_PASSWORD: "${AUTH_SPRING_DATASOURCE_PASSWORD}"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "${AUTH_SPRING_JPA_HIBERNATE_DDL_AUTO}"
      SPRING_SQL_INIT_MODE: "${AUTH_SPRING_SQL_INIT_MODE}"

      JWT_SECRET: "${JWT_SECRET}"

      JAVA_TOOL_OPTIONS: "-javaagent:/otel/opentelemetry-javaagent.jar"

      OTEL_SERVICE_NAME: "auth-service"
      OTEL_RESOURCE_ATTRIBUTES: "deployment.environment=staging"

      OTEL_TRACES_EXPORTER: "otlp"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://signoz-ingester-1:4317"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"

      OTEL_METRICS_EXPORTER: "none"
      OTEL_LOGS_EXPORTER: "none"
      OTEL_TRACES_SAMPLER: "always_on"

    volumes:
      - /opt/opentelemetry/opentelemetry-javaagent.jar:/otel/opentelemetry-javaagent.jar:ro

    extra_hosts:
      - "host.docker.internal:host-gateway"

    networks:
      - backend-api
      - signoz-network

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4005/actuator/health"]
      interval: 10s
      timeout: 15s
      retries: 30
      start_period: 180s


  # =========================
  # Analytics Service
  # =========================

  analytics-service:
    container_name: analytics-service
#    image: ${DOCKERHUB_USERNAME}/analytics-service:${IMAGE_TAG}
    image: ${DOCKERHUB_USERNAME}/analytics-service@${ANALYTICS_SERVICE_DIGEST}
    environment:
      SPRING_PROFILES_ACTIVE: staging

      SPRING_KAFKA_BOOTSTRAP_SERVERS: "${SPRING_KAFKA_BOOTSTRAP_SERVERS}"

      JAVA_TOOL_OPTIONS: "-javaagent:/otel/opentelemetry-javaagent.jar"

      OTEL_SERVICE_NAME: "analytics-service"
      OTEL_RESOURCE_ATTRIBUTES: "deployment.environment=staging"

      OTEL_TRACES_EXPORTER: "otlp"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://signoz-ingester-1:4317"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"

      OTEL_METRICS_EXPORTER: "none"
      OTEL_LOGS_EXPORTER: "none"
      OTEL_TRACES_SAMPLER: "always_on"

    volumes:
      - /opt/opentelemetry/opentelemetry-javaagent.jar:/otel/opentelemetry-javaagent.jar:ro

    extra_hosts:
      - "host.docker.internal:host-gateway"

    networks:
      - backend-api
      - signoz-network

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 15s
      retries: 30
      start_period: 180s


  # =========================
  # Billing Service
  # =========================

  billing-service:
    container_name: billing-service
#    image: ${DOCKERHUB_USERNAME}/billing-service:${IMAGE_TAG}
    image: ${DOCKERHUB_USERNAME}/billing-service@${BILLING_SERVICE_DIGEST}
    environment:
      SPRING_PROFILES_ACTIVE: staging

      JAVA_TOOL_OPTIONS: "-javaagent:/otel/opentelemetry-javaagent.jar"

      OTEL_SERVICE_NAME: "billing-service"
      OTEL_RESOURCE_ATTRIBUTES: "deployment.environment=staging"

      OTEL_TRACES_EXPORTER: "otlp"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://signoz-ingester-1:4317"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"

      OTEL_METRICS_EXPORTER: "none"
      OTEL_LOGS_EXPORTER: "none"
      OTEL_TRACES_SAMPLER: "always_on"

    volumes:
      - /opt/opentelemetry/opentelemetry-javaagent.jar:/otel/opentelemetry-javaagent.jar:ro

    networks:
      - backend-api
      - signoz-network

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4001/actuator/health"]
      interval: 10s
      timeout: 15s
      retries: 30
      start_period: 180s


# =========================
# Networks
# =========================

networks:
  backend-api:
    external: true

  signoz-network:
    external: true